### ISSUE TITLE
Investigate passing a custom server.policy as part of the test for the JSR-77 example

### ISSUE THREAD

**Issue by manorrock** [manorrock/jakartaee-examples#28]

**Comment by manorrock** [comment]
@rmpestano Do you have an idea how to do this? The JSR-77 example is in the eemanagement subdirectory.

**Comment by rmpestano** [comment]
Hi, what's the name and value of the property that need to be passed?

**Comment by manorrock** [comment]
It is not a property that needs to be passed, but rather a whole file so the server can uptake a custom Java policy file. Or put in another way a customization of the JavaEE server itself.

**Comment by rmpestano** [comment]
Well the server is downloaded to /target/server folder maybe we can use @BeforeDeployment event and add the policy file into correct folder. The folder structure will vary from server to server.

I'm not familiar with JSR-77, can you describe the manual steps you do in order to configure the server with the policy file?

Also, If we need the file to be present before the server startup then we may need a custom server distribution (e.g publish the application server zip distribution which already has the server.policy file into a maven repo) and use this custom distribution in our test.

**Comment by manorrock** [comment]
Mmmm, so there is no @BeforeServerStart so we can put the file in the correct place before the server starts? I rather not maintain separate zip bundles ....

**Comment by rmpestano** [comment]
This would be great but i fear this event is not available. Any ideas @lordofthejars, @bartoszmajsak?

**Comment by manorrock** [comment]
Any ideas @lordofthejars, @bartoszmajsak?

**Comment by manorrock** [comment]
Any ideas @lordofthejars, @bartoszmajsak?

**Comment by bartoszmajsak** [comment]
@manorrock There's `SetupContainer` event you could hook into. Maybe worth a shot? Ping me if you need any help.

**Comment by manorrock** [comment]
@rmpestano Can you have a look?

**Comment by rmpestano** [comment]
Yes but I need to know what to `setup`, [as I said before](https://github.com/manorrock/jakartaee-examples/issues/28#issuecomment-451513754) I'm not familiar with JSR-77...

**Comment by mnriem** [comment]
Moved to eclipse-ee4j/jakartaee-examples
